[build]
  command = "npm run generate"
  publish = ".output/public"

[context.production.environment]
  NODE_ENV = 'production'

[[redirects]]
  from = "/_nuxt/*"
  to = "/index.html"
  status = 200

